/** QVL_2.c**Created: 4/25/2019 12:17:42 PM
* Author:LUIS JAVIER QUI;ONEZ VERNAZA (QVLservices)*/
/* Replace with your application code */
#include "avr/io.h"
#include "i2c.h"
#include "SENSOR_CONTROL_AVR.h"
#include "SENSOR_TEMPERATURA_DS1621_AVR.h"
#include "LIBRERIA_DELAY_QVL.h"

#define F_CPU 20000000UL
#define TIMER_RETARDO_TIMER1_EMULATE_DELAY 100
#define TWBR_1 3.5
#define TEMPERATURA_ALTA0 0x14
#define TEMPERATURA_BAJA0 0x0F
#define TEMPERATURA_ALTA1 0x0F
#define TEMPERATURA_BAJA1 0x0A
#define TEMPERATURA_LBS0 0x00
#define ADDRESS__W0 0x90
#define ADDRESS__R0 0x91
#define ADDRESS__W1 0x92
#define ADDRESS__R1 0x93
#define TEMPERATURA_LBS1 0x00
#define BYTE_DE_CONFIGURACION_TEMP 0x02


unsigned char ADDRESS_I2C_WRITE_READ;
int HOME_TIME=0;
int main(void){
CONTROL_CONVERSOR_ANLOGICO_DIGITAL();/*FUNCION PARA CONFIGURAR LOS PARAMETROS INICIALES DEL CONVERTIDOR ADC*/
ENABLE_I2C_PULL_UP(TWBR_1,BIT0,BIT0);/*FUNCION HABILITA EL MODULO I2C JUNT CON LAS RECISTENCIAS PULL UP*/



/*CUNFIGURACION DEL SENSOR DE TEMPERATURA DS1621 COMO TERMOSTATO CON SALIDA DEFINIDA COMO ALTO(POL=1) REGISTRO DE CONFIGURACION*/
F_ACCESO_CONFIGURACION(ADDRESS__W0,BYTE_DE_CONFIGURACION_TEMP);
STOP_COMUNICATION_I2C();
F_ACCESO_TEMPERATURE_ALTA(ADDRESS__W0,TEMPERATURA_ALTA0,TEMPERATURA_LBS0);
STOP_COMUNICATION_I2C();
F_ACCESO_TEMPERATURE_BAJA(ADDRESS__W0,TEMPERATURA_BAJA0,TEMPERATURA_LBS0);
STOP_COMUNICATION_I2C();
F_STAR_CONVERSION_TEMPERATURA(ADDRESS__W0);
STOP_COMUNICATION_I2C();
// /*CUNFIGURACION DEL SENSOR DE TEMPERATURA DS1621 COMO TERMOSTATO CON SALIDA DEFINIDA COMO ALTO(POL=1) REGISTRO DE CONFIGURACION COPIA1*/
F_ACCESO_CONFIGURACION(ADDRESS__W1,BYTE_DE_CONFIGURACION_TEMP);
STOP_COMUNICATION_I2C();
F_ACCESO_TEMPERATURE_ALTA(ADDRESS__W1,TEMPERATURA_ALTA1,TEMPERATURA_LBS1);
STOP_COMUNICATION_I2C();
F_ACCESO_TEMPERATURE_BAJA(ADDRESS__W1,TEMPERATURA_BAJA1,TEMPERATURA_LBS1);
STOP_COMUNICATION_I2C();
F_STAR_CONVERSION_TEMPERATURA(ADDRESS__W1);
STOP_COMUNICATION_I2C();


while (1){
/*ESTA CONDICION IF ME PERMITE CREAR Y AJUSTAR UN RETARDO EN EL ARRANQUE DEL CODIGO DEL LOOP PARA QUE LOS SENSORES PUEDAN CARGAR Y ESTAR LISTOS PARA PODER SER LEIDOS POR EL MICRO*/
if (HOME_TIME==0){
PAUSE_FLUJO(10000,BIT1,BIT0,BIT0);
HOME_TIME=1;}

/*ETAPA1*/
F_LEER_TEMPERATURA(ADDRESS__W0,ADDRESS__R0);/*FUNCION ENCARAGDA DE LEER LA TEMPERATURA USA DOS PARAMETROS */
STOP_COMUNICATION_I2C();/*DETIENE LA COMUNICACION I2C*/
/*ETAPA1*/
PAUSE_FLUJO(TIMER_RETARDO_TIMER1_EMULATE_DELAY,BIT1,BIT0,BIT0);
/*ETAPA1 COPIA1*/
F_LEER_TEMPERATURA(ADDRESS__W1,ADDRESS__R1);/*FUNCION ENCARAGDA DE LEER LA TEMPERATURA USA DOS PARAMETROS COPIA1*/
STOP_COMUNICATION_I2C();/*DETIENE LA COMUNICACION I2C COPIA1*/
// /*ETAPA1 COPIA1*/
/*ETAPA2*/
/*ETAPA2*//*ETAPA3*//*ETAPA3*//*ETAPA4*/
SENSOR0();
PAUSE_FLUJO(TIMER_RETARDO_TIMER1_EMULATE_DELAY,BIT1,BIT0,BIT0);//EN ESTA FUNCION SE PONE EL RETARDO QUE SE CALCULA CON LA FORMULA Y TAMBIEN SE PONE EL PRESCALER
SENSOR1();
PAUSE_FLUJO(TIMER_RETARDO_TIMER1_EMULATE_DELAY,BIT1,BIT0,BIT0);//EN ESTA FUNCION SE PONE EL RETARDO QUE SE CALCULA CON LA FORMULA Y TAMBIEN SE PONE EL PRESCALER
SENSOR2();
PAUSE_FLUJO(TIMER_RETARDO_TIMER1_EMULATE_DELAY,BIT1,BIT0,BIT0);//EN ESTA FUNCION SE PONE EL RETARDO QUE SE CALCULA CON LA FORMULA Y TAMBIEN SE PONE EL PRESCALER
ALERTA();
PAUSE_FLUJO(TIMER_RETARDO_TIMER1_EMULATE_DELAY,BIT1,BIT0,BIT0);//EN ESTA FUNCION SE PONE EL RETARDO QUE SE CALCULA CON LA FORMULA Y TAMBIEN SE PONE EL PRESCALER
/*ETAPA4*/
}



}